[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "word-solver"
version = "1.0.0"
description = "Telegram WordSeek Auto Solver Userbot"
readme = "README.md"
requires-python = ">=3.8"
authors = [
  {name = "Rahul Bhai"}
]

dependencies = [
  "pyrogram",
  "tgcrypto"
]

[tool.setuptools.packages.find]
where = ["."]